package com.cooksys.model;

// Generated Dec 16, 2014 12:16:04 PM by Hibernate Tools 3.4.0.CR1

import java.util.Date;
import java.util.HashSet;
import java.util.Set;

/**
 * Group generated by hbm2java
 */
public class Group implements java.io.Serializable {

	private Integer groupId;
	private Account account;
	private String groupName;
	private Date createdDate;
	private Date updatedDate;
	private Set members = new HashSet(0);

	public Group() {
	}

	public Group(Account account, String groupName, Date createdDate,
			Date updatedDate, Set members) {
		this.account = account;
		this.groupName = groupName;
		this.createdDate = createdDate;
		this.updatedDate = updatedDate;
		this.members = members;
	}

	public Integer getGroupId() {
		return this.groupId;
	}

	public void setGroupId(Integer groupId) {
		this.groupId = groupId;
	}

	public Account getAccount() {
		return this.account;
	}

	public void setAccount(Account account) {
		this.account = account;
	}

	public String getGroupName() {
		return this.groupName;
	}

	public void setGroupName(String groupName) {
		this.groupName = groupName;
	}

	public Date getCreatedDate() {
		return this.createdDate;
	}

	public void setCreatedDate(Date createdDate) {
		this.createdDate = createdDate;
	}

	public Date getUpdatedDate() {
		return this.updatedDate;
	}

	public void setUpdatedDate(Date updatedDate) {
		this.updatedDate = updatedDate;
	}

	public Set getMembers() {
		return this.members;
	}

	public void setMembers(Set members) {
		this.members = members;
	}

}
