package com.cooksys.model;

// Generated Dec 16, 2014 12:16:04 PM by Hibernate Tools 3.4.0.CR1

/**
 * Member generated by hbm2java
 */
public class Member implements java.io.Serializable {

	private Integer memberId;
	private Account account;
	private Group group;
	private Integer status;

	public Member() {
	}

	public Member(Account account, Group group, Integer status) {
		this.account = account;
		this.group = group;
		this.status = status;
	}

	public Integer getMemberId() {
		return this.memberId;
	}

	public void setMemberId(Integer memberId) {
		this.memberId = memberId;
	}

	public Account getAccount() {
		return this.account;
	}

	public void setAccount(Account account) {
		this.account = account;
	}

	public Group getGroup() {
		return this.group;
	}

	public void setGroup(Group group) {
		this.group = group;
	}

	public Integer getStatus() {
		return this.status;
	}

	public void setStatus(Integer status) {
		this.status = status;
	}

}
