package com.cooksys.model;

// Generated Dec 15, 2014 11:39:46 AM by Hibernate Tools 3.4.0.CR1

import java.util.HashSet;
import java.util.Set;

/**
 * Account generated by hbm2java
 */
public class Account implements java.io.Serializable {

	
	private static final long serialVersionUID = 897399537171693004L;
	private Integer accountId;
	private String username;
	private String password;
	private String firstname;
	private String lastname;
	private String urlPicture;
	private Set friendsForFriendeeId = new HashSet(0);
	private Set friendsForFrienderId = new HashSet(0);
	private Set postsForPostedTo = new HashSet(0);
	private Set postsForPostedFrom = new HashSet(0);

	public Account() {
	}

	public Account(String username, String password, String firstname,
			String lastname, String urlPicture, Set friendsForFriendeeId,
			Set friendsForFrienderId, Set postsForPostedTo,
			Set postsForPostedFrom) {
		this.username = username;
		this.password = password;
		this.firstname = firstname;
		this.lastname = lastname;
		this.urlPicture = urlPicture;
		this.friendsForFriendeeId = friendsForFriendeeId;
		this.friendsForFrienderId = friendsForFrienderId;
		this.postsForPostedTo = postsForPostedTo;
		this.postsForPostedFrom = postsForPostedFrom;
	}

	public Account(Integer accountId, String username, String password,
			String firstname, String lastname, String urlPicture,
			Set friendsForFriendeeId, Set friendsForFrienderId,
			Set postsForPostedTo, Set postsForPostedFrom) {
		super();
		this.accountId = accountId;
		this.username = username;
		this.password = password;
		this.firstname = firstname;
		this.lastname = lastname;
		this.urlPicture = urlPicture;
		this.friendsForFriendeeId = friendsForFriendeeId;
		this.friendsForFrienderId = friendsForFrienderId;
		this.postsForPostedTo = postsForPostedTo;
		this.postsForPostedFrom = postsForPostedFrom;
	}

	public Integer getAccountId() {
		return this.accountId;
	}

	public void setAccountId(Integer accountId) {
		this.accountId = accountId;
	}

	public String getUsername() {
		return this.username;
	}

	public void setUsername(String username) {
		this.username = username;
	}

	public String getPassword() {
		return this.password;
	}

	public void setPassword(String password) {
		this.password = password;
	}

	public String getFirstname() {
		return this.firstname;
	}

	public void setFirstname(String firstname) {
		this.firstname = firstname;
	}

	public String getLastname() {
		return this.lastname;
	}

	public void setLastname(String lastname) {
		this.lastname = lastname;
	}

	public String getUrlPicture() {
		return this.urlPicture;
	}

	public void setUrlPicture(String urlPicture) {
		this.urlPicture = urlPicture;
	}

	public Set getFriendsForFriendeeId() {
		return this.friendsForFriendeeId;
	}

	public void setFriendsForFriendeeId(Set friendsForFriendeeId) {
		this.friendsForFriendeeId = friendsForFriendeeId;
	}

	public Set getFriendsForFrienderId() {
		return this.friendsForFrienderId;
	}

	public void setFriendsForFrienderId(Set friendsForFrienderId) {
		this.friendsForFrienderId = friendsForFrienderId;
	}

	public Set getPostsForPostedTo() {
		return this.postsForPostedTo;
	}

	public void setPostsForPostedTo(Set postsForPostedTo) {
		this.postsForPostedTo = postsForPostedTo;
	}

	public Set getPostsForPostedFrom() {
		return this.postsForPostedFrom;
	}

	public void setPostsForPostedFrom(Set postsForPostedFrom) {
		this.postsForPostedFrom = postsForPostedFrom;
	}

}
